version: '3.1'
services:
  mongodb:
    container_name: mongodb
    restart: unless-stopped
    image: 'bitnami/mongodb:latest'
    volumes:
      - ~/database/mongodb/:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=user_name
      - MONGO_INITDB_ROOT_PASSWORD=password
      
networks:
  default:
    external:
      name: database-network
