version: '3.1'
services:
  mongodb:
    image: mongo:4.2
    container_name: mongodb
    restart: unless-stopped	
    volumes:
      - ~/database/mongodb/:/data/db
    ports:
      - 27017:27017
    environment:
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=user_name
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - default

  mongo-exp:
      image: mongo-express
      container_name: express-adt
      restart: unless-stopped	
      depends_on:
        - mongodb
      environment:
        ME_CONFIG_OPTIONS_EDITORTHEME: 'ambiance'
        ME_CONFIG_MONGODB_SERVER: mongodb
        ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
        ME_CONFIG_MONGODB_ADMINUSERNAME: 'user_name'
        ME_CONFIG_MONGODB_ADMINPASSWORD: 'password'
      ports:
        - 3000:8081
      networks:
        - default

networks:
  default:
    external:
      name: database-network        
