version: '3.1'
services:
  postgres:
    container_name: postgres
    restart: unless-stopped
    image: 'bitnami/postgresql:latest'
    volumes:
      - ~/database/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_DATABASE=gobarber
      #- POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=password

      
networks:
  default:
    external:
      name: database-network      
