version: "3.1"
services:
  mongodb:
    container_name: mongodb
    restart: always
    image: mongo:4.2
    volumes:
      - ~/Projetos/database/mongodb/:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: henrique
      MONGO_INITDB_ROOT_PASSWORD: manducamongo
