version: '3.1'
services:
  mongodb:
    container_name: mongodb
    restart: unless-stopped
    image: 'bitnami/mongodb:latest'
    volumes:
      - ~/database/mongodb/:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGODB_ROOT_PASSWORD=roo-password
      - MONGODB_DATABASE=my_database
      - MONGODB_USERNAME=my_user
      - MONGODB_PASSWORD=password
      #- MONGO_INITDB_DATABASE=admin
      #- MONGO_INITDB_ROOT_USERNAME=my_user
      #- MONGO_INITDB_ROOT_PASSWORD=password
      
networks:
  default:
    external:
      name: database-network
