version: '3.1'
services:
  postgres:
    container_name: postgres
    restart: unless-stopped
    image: 'bitnami/postgresql:latest'
    volumes:
      - ~/database/postgres:/bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_DATABASE=stocks
      #- POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=0h6peko62d

networks:
  default:
    external:
      name: vm1
