version: '3.1'
services:
  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:alpine
    volumes:
      - ~/database/redis/:/data
    ports:
      - 6379:6379
      
networks:
  default:
    external:
      name: database-network
